{{- if .Values.cron.enabled -}}
# ------------------- CronJob ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "laravel.names.fullname" . }}-cronjob
  labels:
    {{ include "laravel.labels" . | nindent 6 }}
    {{ include "laravel.labels.cron" . | nindent 6 }}

spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "laravel.names.fullname" . }}-cronjob
          labels:
            {{ include "laravel.labels" . | nindent 12 }}
            {{ include "laravel.labels.cron" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- with .Values.volumes }}
          volumes:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ include "laravel.names.fullname" . }}-cronjob
            image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) | quote }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.cron.command }}
            command:
              - {{ . }}
                {{- end }}
            {{- with .Values.env }}
            env:
              {{- range $k, $v := . }}
              {{- $name := $k }}
              {{- $value := $v }}
              {{- if kindIs "int" $name }}
              {{- $name = required "environment variables as a list of maps require a name field" $value.name }}
              {{- end }}
              - name: {{ quote $name }}
                {{- if kindIs "map" $value -}}
                {{- if hasKey $value "value" }}
                {{- $value = $value.value -}}
                {{- else if hasKey $value "valueFrom" }}
                {{- toYaml $value | nindent 6 }}
                {{- else }}
                {{- dict "valueFrom" $value | toYaml | nindent 6 }}
                {{- end }}
                {{- end }}
                {{- if not (kindIs "map" $value) }}
                {{- if kindIs "string" $value }}
                {{- $value = tpl $value $ }}
                {{- end }}
                value: {{ quote $value }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if or .Values.envFrom }}
            envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 14 }}
            {{- end }}

            {{- with .Values.volumeMounts }}
            volumeMounts:
            {{- toYaml . | nindent 14 }}
            {{- end }}

  {{- end -}}
  {{- end -}}
